import "primevue/resources/themes/lara-light-indigo/theme.css";
import "primevue/resources/themes/lara-light-blue/theme.css";
import "primevue/resources/primevue.min.css";
import "./index.css";

import { createApp } from 'vue';
import PhaseAIApp from './PhaseAIApp.vue';
import { router } from "./router";
import PrimeVue from 'primevue/config';

import AutoComplete from 'primevue/autocomplete';
import Accordion from 'primevue/accordion';
import AccordionTab from 'primevue/accordiontab';
import Avatar from 'primevue/avatar';
import AvatarGroup from 'primevue/avatargroup';
import Badge from 'primevue/badge';
import BlockUI from 'primevue/blockui';
import Button from 'primevue/button';
import Breadcrumb from 'primevue/breadcrumb';
import Calendar from 'primevue/calendar';
import Card from 'primevue/card';
import CascadeSelect from 'primevue/cascadeselect';
import Carousel from 'primevue/carousel';
import Checkbox from 'primevue/checkbox';
import Chip from 'primevue/chip';
import Chips from 'primevue/chips';
import ColorPicker from 'primevue/colorpicker';
import Column from 'primevue/column';
import ColumnGroup from 'primevue/columngroup';
import ConfirmDialog from 'primevue/confirmdialog';
import ConfirmPopup from 'primevue/confirmpopup';
import ContextMenu from 'primevue/contextmenu';
import DataTable from 'primevue/datatable';
import DataView from 'primevue/dataview';
import DataViewLayoutOptions from 'primevue/dataviewlayoutoptions';
import DeferredContent from 'primevue/deferredcontent';
import Dialog from 'primevue/dialog';
import Divider from 'primevue/divider';
import Dock from 'primevue/dock';
import Dropdown from 'primevue/dropdown';
import DynamicDialog from 'primevue/dynamicdialog';
import Fieldset from 'primevue/fieldset';
import FileUpload from 'primevue/fileupload';
import Galleria from 'primevue/galleria';
import Image from 'primevue/image';
import InlineMessage from 'primevue/inlinemessage';
import Inplace from 'primevue/inplace';
import InputSwitch from 'primevue/inputswitch';
import InputText from 'primevue/inputtext';
import InputMask from 'primevue/inputmask';
import InputNumber from 'primevue/inputnumber';
import Knob from 'primevue/knob';
import Listbox from 'primevue/listbox';
import MegaMenu from 'primevue/megamenu';
import Menu from 'primevue/menu';
import Menubar from 'primevue/menubar';
import Message from 'primevue/message';
import MultiSelect from 'primevue/multiselect';
import OrderList from 'primevue/orderlist';
import OrganizationChart from 'primevue/organizationchart';
import OverlayPanel from 'primevue/overlaypanel';
import Paginator from 'primevue/paginator';
import Panel from 'primevue/panel';
import PanelMenu from 'primevue/panelmenu';
import Password from 'primevue/password';
import PickList from 'primevue/picklist';
import ProgressBar from 'primevue/progressbar';
import ProgressSpinner from 'primevue/progressspinner';
import Rating from 'primevue/rating';
import RadioButton from 'primevue/radiobutton';
import Row from 'primevue/row';
import SelectButton from 'primevue/selectbutton';
import ScrollPanel from 'primevue/scrollpanel';
import ScrollTop from 'primevue/scrolltop';
import Skeleton from 'primevue/skeleton';
import Slider from 'primevue/slider';
import Sidebar from 'primevue/sidebar';
import SpeedDial from 'primevue/speeddial';
import SplitButton from 'primevue/splitbutton';
import Splitter from 'primevue/splitter';
import SplitterPanel from 'primevue/splitterpanel';
import Steps from 'primevue/steps';
import TabMenu from 'primevue/tabmenu';
import TieredMenu from 'primevue/tieredmenu';
import Textarea from 'primevue/textarea';
import Toast from 'primevue/toast';
import ToastService from 'primevue/toastservice';
import Toolbar from 'primevue/toolbar';
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';
import Tag from 'primevue/tag';
import Terminal from 'primevue/terminal';
import Timeline from 'primevue/timeline';
import ToggleButton from 'primevue/togglebutton';
import Tree from 'primevue/tree';
import TreeSelect from 'primevue/treeselect';
import TreeTable from 'primevue/treetable';
import TriStateCheckbox from 'primevue/tristatecheckbox';
import VirtualScroller from 'primevue/virtualscroller';

const phaseAIApp = createApp(PhaseAIApp);
phaseAIApp.use(PrimeVue, { ripple: true });
phaseAIApp.use(ToastService);
phaseAIApp.use(router);

phaseAIApp.component('Accordion', Accordion);
phaseAIApp.component('AccordionTab', AccordionTab);
phaseAIApp.component('AutoComplete', AutoComplete);
phaseAIApp.component('Avatar', Avatar);
phaseAIApp.component('AvatarGroup', AvatarGroup);
phaseAIApp.component('Badge', Badge);
phaseAIApp.component('BlockUI', BlockUI);
phaseAIApp.component('Breadcrumb', Breadcrumb);
phaseAIApp.component('Button', Button);
phaseAIApp.component('Calendar', Calendar);
phaseAIApp.component('Card', Card);
phaseAIApp.component('Carousel', Carousel);
phaseAIApp.component('CascadeSelect', CascadeSelect);
phaseAIApp.component('Checkbox', Checkbox);
phaseAIApp.component('Chip', Chip);
phaseAIApp.component('Chips', Chips);
phaseAIApp.component('ColorPicker', ColorPicker);
phaseAIApp.component('Column', Column);
phaseAIApp.component('ColumnGroup', ColumnGroup);
phaseAIApp.component('ConfirmDialog', ConfirmDialog);
phaseAIApp.component('ConfirmPopup', ConfirmPopup);
phaseAIApp.component('ContextMenu', ContextMenu);
phaseAIApp.component('DataTable', DataTable);
phaseAIApp.component('DataView', DataView);
phaseAIApp.component('DataViewLayoutOptions', DataViewLayoutOptions);
phaseAIApp.component('DeferredContent', DeferredContent);
phaseAIApp.component('Dialog', Dialog);
phaseAIApp.component('Divider', Divider);
phaseAIApp.component('Dock', Dock);
phaseAIApp.component('Dropdown', Dropdown);
phaseAIApp.component('DynamicDialog', DynamicDialog);
phaseAIApp.component('Fieldset', Fieldset);
phaseAIApp.component('FileUpload', FileUpload);
phaseAIApp.component('Galleria', Galleria);
phaseAIApp.component('Image', Image);
phaseAIApp.component('InlineMessage', InlineMessage);
phaseAIApp.component('Inplace', Inplace);
phaseAIApp.component('InputMask', InputMask);
phaseAIApp.component('InputNumber', InputNumber);
phaseAIApp.component('InputSwitch', InputSwitch);
phaseAIApp.component('InputText', InputText);
phaseAIApp.component('Knob', Knob);
phaseAIApp.component('Listbox', Listbox);
phaseAIApp.component('MegaMenu', MegaMenu);
phaseAIApp.component('Menu', Menu);
phaseAIApp.component('Menubar', Menubar);
phaseAIApp.component('Message', Message);
phaseAIApp.component('MultiSelect', MultiSelect);
phaseAIApp.component('OrderList', OrderList);
phaseAIApp.component('OrganizationChart', OrganizationChart);
phaseAIApp.component('OverlayPanel', OverlayPanel);
phaseAIApp.component('Paginator', Paginator);
phaseAIApp.component('Panel', Panel);
phaseAIApp.component('PanelMenu', PanelMenu);
phaseAIApp.component('Password', Password);
phaseAIApp.component('PickList', PickList);
phaseAIApp.component('ProgressBar', ProgressBar);
phaseAIApp.component('ProgressSpinner', ProgressSpinner);
phaseAIApp.component('RadioButton', RadioButton);
phaseAIApp.component('Rating', Rating);
phaseAIApp.component('Row', Row);
phaseAIApp.component('SelectButton', SelectButton);
phaseAIApp.component('ScrollPanel', ScrollPanel);
phaseAIApp.component('ScrollTop', ScrollTop);
phaseAIApp.component('Slider', Slider);
phaseAIApp.component('Sidebar', Sidebar);
phaseAIApp.component('Skeleton', Skeleton);
phaseAIApp.component('SpeedDial', SpeedDial);
phaseAIApp.component('SplitButton', SplitButton);
phaseAIApp.component('Splitter', Splitter);
phaseAIApp.component('SplitterPanel', SplitterPanel);
phaseAIApp.component('Steps', Steps);
phaseAIApp.component('TabMenu', TabMenu);
phaseAIApp.component('TabView', TabView);
phaseAIApp.component('TabPanel', TabPanel);
phaseAIApp.component('Tag', Tag);
phaseAIApp.component('Textarea', Textarea);
phaseAIApp.component('Terminal', Terminal);
phaseAIApp.component('TieredMenu', TieredMenu);
phaseAIApp.component('Timeline', Timeline);
phaseAIApp.component('Toast', Toast);
phaseAIApp.component('Toolbar', Toolbar);
phaseAIApp.component('ToggleButton', ToggleButton);
phaseAIApp.component('Tree', Tree);
phaseAIApp.component('TreeSelect', TreeSelect);
phaseAIApp.component('TreeTable', TreeTable);
phaseAIApp.component('TriStateCheckbox', TriStateCheckbox);
phaseAIApp.component('VirtualScroller', VirtualScroller);

phaseAIApp.mount('#app');
